/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.109
 * Generated at: 2021-05-21 10:24:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("\t\t<title>글 상세보기</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/include/css/board.css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/common.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar butChk = 0; // 수정, 삭제 구분용\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#pwdChk\").hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 파일 이미지 출력 */\r\n");
      out.write("\t\t\tvar file = \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\t\tif(file != \"\"){\r\n");
      out.write("\t\t\t\t$(\"#fileImage\").attr({\r\n");
      out.write("\t\t\t\t\tsrc : \"/uploadStorage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\t\t\twidth : \"450px\",\r\n");
      out.write("\t\t\t\t\theight : \"400px\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 목록 버튼 클릭 시 이벤트 */\r\n");
      out.write("\t\t\t$(\"#boardList\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"/board/boardList.som\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 수정 버튼 클릭 시 이벤트 */\r\n");
      out.write("\t\t\t$(\"#updateForm\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t$(\"#msg\").text(\"작성 시 입력한 비밀번호를 입력해주세요.\").css(\"color\", \"#000099\");\r\n");
      out.write("\t\t\t\tbutChk = 1;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 삭제 버튼 클릭 시 이벤트 */\r\n");
      out.write("\t\t\t$(\"#boardDelete\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t$(\"#msg\").text(\"작성 시 입력한 비밀번호를 입력해주세요.\").css(\"color\", \"#000099\");\r\n");
      out.write("\t\t\t\tbutChk = 2;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 비밀번호 확인 버튼 클릭 시 이벤트 */\r\n");
      out.write("\t\t\t$(\"#pwdBut\").click(function(){\r\n");
      out.write("\t\t\t\tpwdConfirm();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction pwdConfirm(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/board/pwdConfirm.som\",\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tdata : $(\"#f_pwd\").serialize(),\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\talert(\"오류가 발생했습니다. 다시 시도해보세요.\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(resultData){\r\n");
      out.write("\t\t\t\t\tvar goUrl = \"\";\r\n");
      out.write("\t\t\t\t\tif(resultData == 0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#msg\").text(\"작성 시 입력한 비밀번호가 일치하지 않습니다.\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#b_pwd\").select();\r\n");
      out.write("\t\t\t\t\t}else if(resultData == 1){\r\n");
      out.write("\t\t\t\t\t\t$(\"#msg\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\tif(butChk == 1){\r\n");
      out.write("\t\t\t\t\t\t\tgoUrl = \"/board/updateForm.som\";\r\n");
      out.write("\t\t\t\t\t\t}else if(butChk == 2){\r\n");
      out.write("\t\t\t\t\t\t\tgoUrl = \"/board/boardDelete.som\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_data\").attr(\"action\", goUrl);\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_data\").submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"boardTit\"><h3>글 상세</h3></div>\r\n");
      out.write("\t\t<form name=\"f_data\" id=\"f_data\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"b_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"b_file\" id=\"b_file\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- 비밀번호 확인 버튼 및 추가 버튼 -->\r\n");
      out.write("\t\t<table id=\"boardPwdBut\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"btd1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"pwdChk\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"f_pwd\" name=\"f_pwd\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"b_num\" id=\"b_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"b_pwd\" id=\"b_pwd\"> 비밀번호 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" id=\"b_pwd\" name=\"b_pwd\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"pwdBut\" value=\"확인\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"btd2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"수정\" id=\"updateForm\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"삭제\" id=\"boardDelete\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"목록\" id=\"boardList\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- 비밀번호 확인 버튼 및 추가 버튼 끝 -->\r\n");
      out.write("\t\t<div id=\"boardDetail\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"25%\"/>\r\n");
      out.write("\t\t\t\t\t<col width=\"25%\"/>\r\n");
      out.write("\t\t\t\t\t<col width=\"25%\"/>\r\n");
      out.write("\t\t\t\t\t<col width=\"25%\"/>\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"ac\">작성자</td>\r\n");
      out.write("\t\t\t\t\t\t<td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"ac\">작성일</td>\r\n");
      out.write("\t\t\t\t\t\t<td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_insertdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"ac\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"ctr\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"ac\">내용</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"ctr\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"ac\">첨부파일 </td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><img id=\"fileImage\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "reply.jsp", out, false);
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/jsp/board/boardDetail.jsp(19,15) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDetail.b_file}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
